# Drupal
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#

version: '3'
services:
  drupal8:
    image: drupal
    ports:
      - "8080:80"
    build: .
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Sup3r88
      - VIRTUAL_HOST=live.daveferrara1.com
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    volumes:
      - /home/docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Sup3r88
    restart: always